name-template: "Xiao Ai Patched v$NEXT_PATCH_VERSION"
tag-template: "$NEXT_PATCH_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"
change-template: "* #$NUMBER - $TITLE"
categories:
  - title: 'Packages'
    labels:
      - 'packages'
  - title: 'Speaker patches'
    labels:
      - 'LX01'
      - 'LX06'
      - 'L09A'
      - 'L09B'
      - 'S12'
  - title: 'Features'
    labels:
      - 'feature'
      - 'research'
      - 'enhancement'
  - title: 'Bugs killed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

autolabeler:
  - label: 'packages'
    files:
      - 'packages.sh'
      - 'packages/**'
  - label: 'research'
    files:
      - 'research/**'
  - label: 'LX06'
    title:
      - '/lx06/i'
      - '/l06a/i'
  - label: 'LX01'
    title:
      - '/lx01/i'
  - label: 'L09A'
    title:
      - '/l09a/i'
  - label: 'L09B'
    title:
      - '/l09b/i'


template: |
  ## Changelog
  $CHANGES
