#!/bin/sh /etc/rc.common

#before wireless
START=75

USE_PROCD=1
if [ ! -f "/data/bt/debug" ];then
DEBUG=0
else
DEBUG=`cat /data/bt/debug`
fi
PROG1=/usr/bin/bluealsa
PROG2=/usr/bin/bluealsa-aplay
PROG3=/usr/bin/bluez_mibt_classical
PROG5=/usr/bin/mico_ble_service

function bluealsa_start() {
	procd_open_instance
	if [ $DEBUG = "1" ]; then
		procd_set_param command "$PROG1" -i hci0 -p a2dp-sink -S
	else
		procd_set_param command "$PROG1" -i hci0 -p a2dp-sink
	fi
	procd_append_param respawn 3600
	procd_append_param respawn 5
	procd_append_param respawn 5
	procd_close_instance

	# procd_open_instance
	# procd_set_param command "$PROG2" 00:00:00:00:00:00 -vv -i hci0 -d default --profile-a2dp --stereo-audio
	# procd_set_param respawn
	# procd_append_param respawn 3600
	# procd_append_param respawn 5
	# procd_append_param respawn 5
	# procd_close_instance
}

function bluez_mibt_classical_start() {
	procd_open_instance
	procd_set_param command "$PROG3"
	procd_append_param respawn 3600
	procd_append_param respawn 5
	procd_append_param respawn 5
	procd_close_instance
}

# function bluez_mible_start() {
# 	procd_open_instance
# 	procd_set_param command "$PROG5"
# 	procd_append_param respawn 3600
# 	procd_append_param respawn 5
# 	procd_append_param respawn 5
# 	procd_close_instance
# }

function bluez_start() {
		echo "Start	bluealsa"
		bluealsa_start
		sleep 2
		echo "Start	bluez_mibt_classical"
		bluez_mibt_classical_start
		[ ! -f "/data/status/config_done" ] && {
			# echo "mibt Start BLE"
			# bluez_mibt_ble_start
			/etc/init.d/bluetooth_ble start
		}
}

start_service() {
	bluez_start
}
