#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

#start after dbus (60)
START=62
USE_PROCD=1
if [ ! -f "/data/bt/debug" ];then
DEBUG=0
else
DEBUG=`cat /data/bt/debug`
fi
PROG=/usr/bin/bluetoothd
conf_dir=/data/bt/bluez/

function bluetoothd_start() {
    if [ $DEBUG = "1" ]; then
        $PROG -C -d -n 2>/tmp/bluetoothd.log &
        echo "Start	hcidump"
        rm /tmp/hci.cfa > /dev/null 2>&1
        hcidump -w /tmp/hci.cfa &
        cat /proc/kmsg >/tmp/dmsg.log &
    else
        procd_open_instance
        procd_set_param command "$PROG" -n
        procd_set_param respawn 3600 5 0
        procd_close_instance
    fi
}

start_service() {
    echo "Start	rtk_hciattach"
    echo 0 > /sys/class/rfkill/rfkill0/state
    sleep 1
    echo 1 > /sys/class/rfkill/rfkill0/state
    sleep 1
    if [ $DEBUG = "1" ]; then
        rtk_hciattach -n -s 115200 ttyS1 rtk_h5 > /tmp/rtk_hciattach.log 2>&1 &
    else
        rtk_hciattach -n -s 115200 ttyS1 rtk_h5 > /dev/null 2>&1 &
    fi
    sleep 2
    btmgmt power on

    if [ ! -d $conf_dir/bluetooth ];then
        /bin/mkdir -p $conf_dir/bluetooth
        /bin/chmod 777 $conf_dir/bluetooth
    else
        if [ -f $conf_dir/bluetooth/main.conf ];then
            rm -rf $conf_dir/bluetooth/main.conf
        fi
    fi
    cp /etc/bluetooth/* $conf_dir/bluetooth/

    if [ ! -d $conf_dir/lib/bluetooth ];then
        /bin/mkdir -p $conf_dir/lib/bluetooth
        /bin/chmod 777 $conf_dir/lib/bluetooth
    fi

    BT_NAME=$(micocfg_bt_name)
    BT_ALIAS=$(micocfg_bt_alias)
    if [ x"$BT_ALIAS" != x"" ];then
         BT_NAME=$BT_ALIAS
    fi

    sed -i "s|Name = .*|Name = ${BT_NAME}|" $conf_dir/bluetooth/main.conf
    echo "Start	bluetoothd"
    bluetoothd_start
}

stop_service() {
    echo "Stop	rtk_hciattach"
    killall -9 rtk_hciattach

    if [ $DEBUG = "1" ]; then
        echo "Stop	hcidump"
        killall hcidump
        rm -rf /tmp/hci.cfa
        rm -rf /tmp/rtk_hciattach.log
        rm -rf /tmp/dmsg.log
        kill -9 $(pidof bluetoothd)
    fi
}
