#!/bin/sh /etc/rc.common

#before wireless
# START=75
# STOP=30

USE_PROCD=1

PROG1=/usr/bin/mico_ble_service

function bluez_mibt_ble_start() {
	procd_open_instance
	procd_set_param command "$PROG1"
	procd_append_param respawn 3600
	procd_append_param respawn 5
	procd_append_param respawn 5
	procd_close_instance
}

start_service() {
	echo "mibt Start BLE"
	hciconfig hci0 reset
	sleep 2
	
	[ ! -f /data/status/config_done ] && {
		killall hcidump >/dev/null 2>&1
		rm /tmp/ble_hci.cfa
		hcidump -Rw /tmp/ble_hci.cfa >/dev/null 2>&1 &
	}

	bluez_mibt_ble_start
}
